version: '3.3'

services:
  # MySQL
  db:
    image: mysql:5.7
    restart: always
    hostname: local_db
    container_name: mysql_morning_code
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: morning_code
      MYSQL_USER: mc_rw
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
      BIND-ADDRESS: 0.0.0.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    tty: true
