/*
 * This file is generated by jOOQ.
 */
package io.morningcode.db;


import io.morningcode.db.tables.Blog;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in morning_code
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>morning_code.blog</code>.
     */
    public static final Blog BLOG = Blog.BLOG;
}
